#hash((absolute-installation? . #t)
      (apps-dir
       .
       "/tmp/racket-issue-4133/layer-b/share/applications")
      (bin-dir
       .
       "/tmp/racket-issue-4133/layer-b/bin")
      (bin-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/bin"
        "/tmp/racket-issue-4133/racket/bin"))
      (build-stamp . "")
      (config-tethered-apps-dir
       .
       "/tmp/racket-issue-4133/layer-b/share/applications")
      (config-tethered-console-bin-dir
       .
       "/tmp/racket-issue-4133/layer-b/bin")
      (config-tethered-gui-bin-dir
       .
       "/tmp/racket-issue-4133/layer-b/bin")
      (doc-dir
       .
       "/tmp/racket-issue-4133/layer-b/share/doc/racket")
      (doc-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/share/doc/racket"
        "/tmp/racket-issue-4133/racket/doc"))
      (include-dir
       .
       "/tmp/racket-issue-4133/layer-b/include/racket")
      (include-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/include/racket"
        "/tmp/racket-issue-4133/racket/include"))
      (installation-name . "8.3.900-guix")
      (lib-dir
       .
       "/tmp/racket-issue-4133/layer-b/lib/racket")
      (lib-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/lib/racket"
        "/tmp/racket-issue-4133/racket/lib"))
      (links-file
       .
       "/tmp/racket-issue-4133/layer-b/lib/racket/links.rktd")
      (links-search-files
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/lib/racket/links.rktd"
        "/tmp/racket-issue-4133/racket/share/links.rktd"))
      (man-dir
       .
       "/tmp/racket-issue-4133/layer-b/share/man")
      (man-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/share/man"
        "/tmp/racket-issue-4133/racket/share/man"))
      (pkgs-dir
       .
       "/tmp/racket-issue-4133/layer-b/lib/racket/pkgs")
      (pkgs-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/lib/racket/pkgs"
        "/tmp/racket-issue-4133/racket/share/pkgs"))
      (share-dir
       .
       "/tmp/racket-issue-4133/layer-b/share/racket")
      (share-search-dirs
       .
       (#f
        "/tmp/racket-issue-4133/layer-a/share/racket"
        "/tmp/racket-issue-4133/racket/share")))
